# Generated by Django 4.2.7 on 2023-11-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('materials', models.TextField()),
                ('articul', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=10)),
            ],
        ),
    ]
